### ISSUE TITLE
Redirect Chain

### ISSUE THREAD

**Issue by xbbshampoo** [extractr-io/puphpeteer#6]
Hi, is there any way I can access the redirect chains thru puppeter?

```
                $puppeteer = new Puppeteer([
			'read_timeout' => 100,
			'debug'        => true,
		]);

		$browser = $puppeteer->launch([
			'headless'          => true,
			'ignoreHTTPSErrors' => true,
		]);

		$page     = $browser->newPage();
		$response = $page->goto('http://invol.co/aff_m?offer_id=1664&aff_id=1024&source=deeplink_generator', [ 'waitUntil' => 'networkidle0' ]);

		var_dump($response->request->redirectChain());

		$browser->close();
```

I just manage to get null from the var_dump

**Comment by nesk** [comment]
Running your code throws the following exception instead of `null`:

```
PHP Fatal error:  Uncaught ExtractrIo\Rialto\Exceptions\Node\FatalException: "request.redirectChain is not a function"

Error: "request.redirectChain is not a function"
    at Instruction.callResourceMethod (/Users/johann/Development/puphpeteer/vendor/extractr-io/rialto/src/node-process/Instruction.js:193:23)
    at Instruction.execute (/Users/johann/Development/puphpeteer/vendor/extractr-io/rialto/src/node-process/Instruction.js:161:31)
    at PuppeteerConnectionDelegate.handleInstruction (/Users/johann/Development/puphpeteer/src/PuppeteerConnectionDelegate.js:33:39)
    at Connection.handleSocketData (/Users/johann/Development/puphpeteer/vendor/extractr-io/rialto/src/node-process/Connection.js:64:23)
    at Socket.socket.on.data (/Users/johann/Development/puphpeteer/vendor/extractr-io/rialto/src/node-process/Connection.js:48:18)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:258:13)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at in /Users/johann/Development/puphpeteer/vendor/extractr-io/rialto/src/ProcessSupervisor.php on line 230
```

This is because the `$response->request` is a function, not a property, then it should be called like this:

```php
var_dump($response->request()->redirectChain());
```

This is explained [in Puppeteer's documentation](https://github.com/GoogleChrome/puppeteer/blob/v1.3.0/docs/api.md#responserequest).
